### ISSUE TITLE
Pins on maps are not visible to players

### ISSUE THREAD

**Issue by JBerkvens** [worldanvil/worldanvil-bug-tracker#90]
**World Anvil Username**: Moridrin

**World / Campaign / RPG Character / Manuscript Title**: The World

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/the-world-moridrin/map/9313c1d5-661e-41c9-92f0-7d54df7e2aba

**Describe the Issue**
I have a map with markers on them to give an easy overview of the settlement and to allow players to open the articles from the buildings by clicking on them on the map. However, I see the markers just fine but even though the map, the markers, the marker group and everything else I could find is set to public, the players only see the map and do not see any of the markers.

**To Reproduce**
1. Create a map and add markers
2. Log in as a player or use incognito to not be signed in at all
3. You will not see any markers

**Expected behavior**
I expect markers that are set to public to show on the map if someone is not signed in.

**Screenshots**
A player sees this:
![image](https://user-images.githubusercontent.com/6276155/112139201-ca65e300-8bd2-11eb-850f-c021a1b16da9.png)
I see this:
![image](https://user-images.githubusercontent.com/6276155/112139299-e5385780-8bd2-11eb-8b18-4d13cf67977d.png)
Marker Settings:
![image](https://user-images.githubusercontent.com/6276155/112139475-16b12300-8bd3-11eb-8458-52dc1333395e.png)
Marker Group Settings:
![image](https://user-images.githubusercontent.com/6276155/112139563-321c2e00-8bd3-11eb-80a0-b5f9094d08fa.png)
Map Settings:
![image](https://user-images.githubusercontent.com/6276155/112139633-4d873900-8bd3-11eb-843c-3519712e2c2e.png)

**Comment by iamromeo** [comment]
If your map is private (or in a private world) the public/private of markers will make no difference since the privacy of the world/map will take precedence. 
You need to set the subscriber group that you wish to use on your markers. 
1. It's now MUCH easier since I JUST released the quick sub group change for markers
2. You might want to make "Party" a default group in your world, so it's automatically assigned. Just don't forget to remove it for your personal notes.

**Comment by JBerkvens** [comment]
Hello, thanks for the quick reply. However after a lot more tests I still cannot get any markers to show up on the maps when signed in as a player.
Also just to clarify, everything should be public (world, campaign, map, marker group, and markers) but I finally decided to take a closer look at something that I can view: the console in the browser and indeed I found something that I think still indicates a bug:
When I have the most default marker I see a blue pin, but when my players view the page they do not see the marker and the console logs these errors:
![image](https://user-images.githubusercontent.com/6276155/112179482-06ad3980-8bfb-11eb-8f71-bd6ef35e8252.png)
Now when I remove the marker and create a different one (a "Moon, Black" as pin type), the player now gets the error I was expecting:
![image](https://user-images.githubusercontent.com/6276155/112179887-5b50b480-8bfb-11eb-8504-36b93b7e6848.png)
There seems to be a bug in the JS causing something to crash and not display the pins.
With multiple pins it only shows an error for first pin and still does not display any other pins.

**Comment by iamromeo** [comment]
You have an icon called Black Moon, or you used to? This icon is added to the map but not found. This is the reason the map is crushing. This is certainly a custom marker :) 
In order to fix it, find which pin is using it and change its marker. It should be fairly easy with the new markers list
